# Generated by Django 5.1.4 on 2025-05-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticField',
            fields=[
                ('sem_field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sem_field_name_eng', models.CharField(max_length=255)),
                ('sem_field_name_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'semantic_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_birthdate', models.DateTimeField(blank=True, null=True)),
                ('author_deathdate', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_nationality', models.CharField(max_length=255)),
                ('biography', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='LitTrans',
            fields=[
                ('lit_trans_type', models.IntegerField()),
                ('lit_trans_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lit_trans_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('lit_trans_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lit_trans',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('date_publication', models.IntegerField()),
                ('language', models.IntegerField()),
                ('type_source', models.IntegerField()),
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=255)),
                ('source_name_english', models.CharField(max_length=255)),
                ('source_name_original', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('language', models.IntegerField()),
                ('score_h_figures', models.IntegerField()),
                ('score_m_figures', models.IntegerField()),
                ('score_objects', models.IntegerField()),
                ('score_places', models.IntegerField()),
                ('score_tribes', models.IntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Propernoun',
            fields=[
                ('propernoun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cultural_area', models.BigIntegerField(blank=True, null=True)),
                ('word_theme', models.BigIntegerField(blank=True, null=True)),
                ('current_name', models.CharField(max_length=255)),
                ('etymo_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=45, null=True)),
                ('place', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('short_descr_eng', models.CharField(blank=True, max_length=150, null=True)),
                ('short_descr_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('descr_eng', models.CharField(blank=True, max_length=3000, null=True)),
                ('descr_fr', models.CharField(blank=True, max_length=3000, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('img_caption', models.CharField(max_length=255)),
                ('lit_trans', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.littrans')),
            ],
            options={
                'db_table': 'propernoun',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quote_text', models.CharField(max_length=255)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.source')),
            ],
            options={
                'db_table': 'quote',
            },
        ),
        migrations.CreateModel(
            name='WordStem',
            fields=[
                ('gender', models.IntegerField(blank=True, null=True)),
                ('word_class', models.IntegerField(blank=True, null=True)),
                ('word_stem_language', models.IntegerField()),
                ('word_stem_name', models.CharField(max_length=255)),
                ('first_occurence', models.IntegerField()),
                ('word_stem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descr_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('descr_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_words_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_words_fr', models.CharField(max_length=255)),
                ('child_stems', models.ManyToManyField(blank=True, related_name='parent_stems_reverse', to='geriadur_api_django.wordstem')),
                ('sem_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.semanticfield')),
            ],
            options={
                'db_table': 'word_stem',
            },
        ),
        migrations.CreateModel(
            name='WordStemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geriadur_api_django.source')),
                ('word_stem', models.ForeignKey(db_column='word_stem_id', on_delete=django.db.models.deletion.CASCADE, to='geriadur_api_django.wordstem')),
            ],
            options={
                'db_table': 'word_stem_source',
                'unique_together': {('source', 'word_stem')},
            },
        ),
        migrations.AddField(
            model_name='wordstem',
            name='source',
            field=models.ManyToManyField(through='geriadur_api_django.WordStemSource', to='geriadur_api_django.source'),
        ),
        migrations.CreateModel(
            name='WordStemPropernoun',
            fields=[
                ('word_stem_pc_key', models.IntegerField(primary_key=True, serialize=False)),
                ('propernoun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geriadur_api_django.propernoun')),
                ('word_stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geriadur_api_django.wordstem')),
            ],
            options={
                'db_table': 'word_stem_propernoun',
                'unique_together': {('word_stem_pc_key', 'propernoun_id')},
            },
        ),
        migrations.CreateModel(
            name='SourceAuthor',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geriadur_api_django.author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.source')),
            ],
            options={
                'db_table': 'source_author',
                'unique_together': {('author', 'source')},
            },
        ),
        migrations.CreateModel(
            name='WordStemQuote',
            fields=[
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geriadur_api_django.quote')),
                ('word_stem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.wordstem')),
            ],
            options={
                'db_table': 'word_stem_quote',
                'unique_together': {('quote', 'word_stem')},
            },
        ),
    ]
