# Generated by Django 5.0.6 on 2024-11-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_birthdate', models.DateTimeField(blank=True, null=True)),
                ('author_deathdate', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_nationality', models.CharField(max_length=255)),
                ('biography', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LitTrans',
            fields=[
                ('lit_trans_type', models.IntegerField()),
                ('lit_trans_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lit_trans_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('lit_trans_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lit_trans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propernoun',
            fields=[
                ('propernoun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cultural_area', models.BigIntegerField(blank=True, null=True)),
                ('word_theme', models.BigIntegerField(blank=True, null=True)),
                ('current_name', models.CharField(max_length=255)),
                ('etymo_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=45, null=True)),
                ('place', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('short_descr_eng', models.CharField(blank=True, max_length=150, null=True)),
                ('short_descr_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('descr_eng', models.CharField(blank=True, max_length=3000, null=True)),
                ('descr_fr', models.CharField(blank=True, max_length=3000, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('img_caption', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'propernoun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quote_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticField',
            fields=[
                ('sem_field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sem_field_name_eng', models.CharField(max_length=255)),
                ('sem_field_name_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'semantic_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('date_publication', models.IntegerField()),
                ('language', models.IntegerField()),
                ('type_source', models.IntegerField()),
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=255)),
                ('source_name_english', models.CharField(max_length=255)),
                ('source_name_original', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('language', models.IntegerField()),
                ('score_h_figures', models.IntegerField()),
                ('score_m_figures', models.IntegerField()),
                ('score_objects', models.IntegerField()),
                ('score_places', models.IntegerField()),
                ('score_tribes', models.IntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStem',
            fields=[
                ('gender', models.IntegerField(blank=True, null=True)),
                ('word_class', models.IntegerField(blank=True, null=True)),
                ('word_stem_language', models.IntegerField()),
                ('word_stem_name', models.CharField(max_length=255)),
                ('first_occurence', models.IntegerField()),
                ('word_stem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descr_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('descr_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_words_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_words_fr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'word_stem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStemPropernoun',
            fields=[
                ('word_stem_pc_key', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'word_stem_propernoun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'word_stem_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceAuthor',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geriadur_api_django.author')),
            ],
            options={
                'db_table': 'source_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStemQuote',
            fields=[
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geriadur_api_django.quote')),
            ],
            options={
                'db_table': 'word_stem_quote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordStemParent',
            fields=[
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geriadur_api_django.wordstem')),
            ],
            options={
                'db_table': 'word_stem_parent',
                'managed': False,
            },
        ),
    ]
