# Generated by Django 5.1.4 on 2025-05-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordstem',
            options={},
        ),
        migrations.DeleteModel(
            name='WordStemParent',
        ),
    ]
