# Generated by Django 5.1.4 on 2025-07-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Wordclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordclass', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'wordclass',
            },
        ),
        migrations.AddField(
            model_name='wordstem',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.language'),
        ),
        migrations.AddField(
            model_name='wordstem',
            name='wordclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.wordclass'),
        ),
    ]
