# Generated by Django 5.1.4 on 2025-05-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geriadur_api_django", "0002_alter_wordstem_options_delete_wordstemparent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={},
        ),
        migrations.AlterModelOptions(
            name="littrans",
            options={},
        ),
        migrations.AlterModelOptions(
            name="propernoun",
            options={},
        ),
        migrations.AlterModelOptions(
            name="quote",
            options={},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sourceauthor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelOptions(
            name="wordstempropernoun",
            options={},
        ),
        migrations.AlterModelOptions(
            name="wordstemquote",
            options={},
        ),
        migrations.AlterModelOptions(
            name="wordstemsource",
            options={},
        ),
    ]
