# Generated by Django 5.1.4 on 2025-07-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0002_language_wordclass_wordstem_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.AddField(
            model_name='wordstem',
            name='w_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.gender'),
        ),
    ]
