# Generated by Django 5.1.4 on 2025-07-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0003_gender_wordstem_w_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='date_publication',
            new_name='edition_date',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_name_english',
            new_name='eng_title',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_name_original',
            new_name='orig_title',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='type_source',
            new_name='type',
        ),
    ]
