# Generated by Django 5.1.4 on 2025-07-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0004_rename_date_publication_source_edition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='studied_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sources_as_studied', to='geriadur_api_django.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='writing_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sources_as_writing', to='geriadur_api_django.language'),
            preserve_default=False,
        ),
    ]
