# Generated by Django 5.1.4 on 2025-07-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0005_source_studied_language_source_writing_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choosen_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.language'),
        ),
    ]
