# Generated by Django 5.1.4 on 2025-07-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geriadur_api_django', '0006_user_choosen_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('entity_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.entityfield')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geriadur_api_django.language')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'field', 'language'], name='geriadur_ap_entity__72acf1_idx')],
                'unique_together': {('entity_type', 'entity_id', 'field', 'language')},
            },
        ),
    ]
