# Generated by Django 5.1.4 on 2025-07-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0009_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_deathdate',
            new_name='deathdate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='littrans',
            old_name='lit_trans_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='littrans',
            old_name='lit_trans_eng',
            new_name='name_eng',
        ),
        migrations.RenameField(
            model_name='littrans',
            old_name='lit_trans_fr',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='littrans',
            old_name='lit_trans_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='propernoun',
            old_name='descr_eng',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='propernoun',
            old_name='short_descr_eng',
            new_name='short_descr',
        ),
        migrations.RenameField(
            model_name='semanticfield',
            old_name='sem_field_name_eng',
            new_name='name_eng',
        ),
        migrations.RenameField(
            model_name='semanticfield',
            old_name='sem_field_name_fr',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='eng_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='wordclass',
            old_name='wordclass',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wordstem',
            old_name='ref_words_eng',
            new_name='translation',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_nationality',
        ),
    ]
