# Generated by Django 5.1.4 on 2025-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0010_rename_author_birthdate_author_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstem',
            name='eng_translations',
            field=models.ManyToManyField(related_name='eng_wordstems', to='geriadur_api_django.translation'),
        ),
        migrations.AddField(
            model_name='wordstem',
            name='fr_translations',
            field=models.ManyToManyField(related_name='fr_wordstems', to='geriadur_api_django.translation'),
        ),
    ]
