# Generated by Django 5.1.4 on 2025-12-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geriadur_api_django', '0011_wordstem_eng_translations_wordstem_fr_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geriadur_api_django.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='studied_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources_as_studied', to='geriadur_api_django.language'),
        ),
        migrations.AlterField(
            model_name='source',
            name='writing_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources_as_writing', to='geriadur_api_django.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geriadur_api_django.entityfield'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geriadur_api_django.language'),
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geriadur_api_django.language'),
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='sem_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geriadur_api_django.semanticfield'),
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='w_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geriadur_api_django.gender'),
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='wordclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geriadur_api_django.wordclass'),
        ),
    ]
