# Generated by Django 5.1.4 on 2026-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0012_alter_quote_source_alter_source_studied_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='littrans',
            name='name_br',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
