# Generated by Django 5.1.4 on 2026-02-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0013_littrans_name_br'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=15)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geriadur_api_django.language')),
            ],
            options={
                'db_table': 'language_translation',
                'unique_together': {('language', 'lang')},
            },
        ),
    ]
