# Generated by Django 5.1.4 on 2026-03-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0014_remove_language_abbreviation_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordstemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geriadur_api_django.language')),
            ],
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='eng_translations',
            field=models.ManyToManyField(related_name='eng_wordstems', to='geriadur_api_django.wordstemtranslation'),
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='fr_translations',
            field=models.ManyToManyField(related_name='fr_wordstems', to='geriadur_api_django.wordstemtranslation'),
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
