# Generated by Django 5.1.4 on 2026-03-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0015_wordstemtranslation_alter_wordstem_eng_translations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordstem',
            old_name='fr_translations',
            new_name='translations',
        ),
        migrations.RemoveField(
            model_name='wordstem',
            name='eng_translations',
        ),
    ]
