# Generated by Django 5.1.4 on 2026-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0016_rename_fr_translations_wordstem_translations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordstem',
            name='ref_words_fr',
        ),
        migrations.RemoveField(
            model_name='wordstem',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='wordstem',
            name='word_stem_language',
        ),
        migrations.AlterField(
            model_name='wordstem',
            name='first_occurence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
