# Generated by Django 5.1.4 on 2026-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geriadur_api_django', '0017_remove_wordstem_ref_words_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_focus',
            field=models.BooleanField(default=True),
        ),
    ]
